

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sklep.Models.db
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class sklepEntities : DbContext
{
    public sklepEntities()
        : base("name=sklepEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Users> Users { get; set; }

    public virtual DbSet<Categories> Categories { get; set; }

    public virtual DbSet<Deliveries> Deliveries { get; set; }

    public virtual DbSet<Statuses> Statuses { get; set; }

    public virtual DbSet<Comments> Comments { get; set; }

    public virtual DbSet<Images> Images { get; set; }

    public virtual DbSet<Orders> Orders { get; set; }

    public virtual DbSet<Products> Products { get; set; }

    public virtual DbSet<ProductsOfOrders> ProductsOfOrders { get; set; }

    public virtual DbSet<Payments> Payments { get; set; }

    public virtual DbSet<Scrapers> Scrapers { get; set; }

}

}

