
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sklep.Models.db
{

using System;
    using System.Collections.Generic;
    
public partial class Orders
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Orders()
    {

        this.ProductsOfOrders = new HashSet<ProductsOfOrders>();

    }


    public int OrderID { get; set; }

    public int UserID { get; set; }

    public System.DateTime Date { get; set; }

    public string OrderPath { get; set; }

    public Nullable<int> WhoModified { get; set; }

    public Nullable<System.DateTime> LastTimeModified { get; set; }

    public Nullable<decimal> PriceN { get; set; }

    public Nullable<decimal> PriceB { get; set; }

    public string DeliverStreet { get; set; }

    public string DeliverNumOfHouse { get; set; }

    public string DeliverPostCode { get; set; }

    public string DeliverCity { get; set; }

    public string InvoicePath { get; set; }

    public string NameDelivery { get; set; }

    public Nullable<decimal> PriceNDelivery { get; set; }

    public Nullable<decimal> VATDelivery { get; set; }

    public string NamePayment { get; set; }

    public Nullable<decimal> PriceNPayment { get; set; }

    public Nullable<decimal> VatPayment { get; set; }

    public string Status { get; set; }

    public string Name { get; set; }

    public string Surname { get; set; }



    public virtual Users Users { get; set; }

    public virtual Users Users1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductsOfOrders> ProductsOfOrders { get; set; }

}

}
