
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sklep.Models.db
{

using System;
    using System.Collections.Generic;
    
public partial class Payments
{

    public int PaymentID { get; set; }

    public string Name { get; set; }

    public decimal PriceN { get; set; }

    public decimal VAT { get; set; }

}

}
