
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sklep.Models.db
{

using System;
    using System.Collections.Generic;
    
public partial class Products
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Products()
    {

        this.Comments = new HashSet<Comments>();

        this.Images = new HashSet<Images>();

        this.ProductsOfOrders = new HashSet<ProductsOfOrders>();

        this.Scrapers = new HashSet<Scrapers>();

    }


    public int ProductID { get; set; }

    public int CategoryID { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Specification { get; set; }

    public int Quantity { get; set; }

    public decimal Vat { get; set; }

    public bool Recommended1 { get; set; }

    public decimal PriceN { get; set; }

    public string CodeProduct { get; set; }

    public bool IsShowed { get; set; }

    public Nullable<decimal> OldPriceN { get; set; }



    public virtual Categories Categories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Comments> Comments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Images> Images { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductsOfOrders> ProductsOfOrders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Scrapers> Scrapers { get; set; }

}

}
