
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Sklep.Models.db
{

using System;
    using System.Collections.Generic;
    
public partial class Scrapers
{

    public int Id { get; set; }

    public int ProductID { get; set; }

    public string XKomPrice { get; set; }

    public Nullable<System.DateTime> DateLastUpdate { get; set; }

    public Nullable<decimal> DifferencePrice { get; set; }

    public string VobisPrice { get; set; }

    public string VobistLink { get; set; }

    public string AlsenPrice { get; set; }

    public string AlsentLink { get; set; }

    public string CeneoPrice { get; set; }

    public string CeneoLink { get; set; }

    public string XKomLinkChecked { get; set; }

    public string VobistLinkChecked { get; set; }

    public string AlsentLinkChecked { get; set; }

    public string CeneoLinkChecked { get; set; }

    public string XKomLink { get; set; }



    public virtual Products Products { get; set; }

}

}
